### ISSUE TITLE
Not showing Networks

### ISSUE THREAD

**Issue by maatthc** [colemancda/Wi-Fi-Crack#3]
Hi there,
I've compiled the code and executed the app without any issue.
When I execute it, it asks me for the Interface, and on the next page it doesn't list any Network. I have AirRadar installed and it shows dozens of networks.
I'm using a MacBook Pro Retina, 13-inch Late 2012, last version of MacOS and Xcode:
Darwin maats-mbp 13.1.0 Darwin Kernel Version 13.1.0: Wed Apr  2 23:52:02 PDT 2014; root:xnu-2422.92.1~2/RELEASE_X86_64 x86_64 .
I've tried to understand the code but I'm not able to identify where that network list come from. From the command line the following command lists again dozen of networks:

sudo /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport scan

**Comment by colemancda** [comment]
the app will only list WEP networks

**Comment by colemancda** [comment]
The app uses CoreWLAN for listing available networks and only lists WEP networks
