### ISSUE TITLE
Can't see any network

### ISSUE THREAD

**Issue by sg-s** [colemancda/Wi-Fi-Crack#6]
I select my interface, then it tries to scan for networks, but doesn't see anything. Help? 

I'm on 10.10.1

I haven't installed aircrack-ng or anything else. Is that required?

![screen shot 2014-12-05 at 7 06 09 pm](https://cloud.githubusercontent.com/assets/6005346/5325143/c8c5a602-7cb1-11e4-9020-853c832af496.png)

**Comment by colemancda** [comment]
It only scans for WEP networks. You must not have a WEP network in range.

**Comment by sg-s** [comment]
ah i see. thanks for the reply. anything like this for WPA?

**Comment by colemancda** [comment]
Afraid not. KisMac (http://kismac-ng.org http://kismac-ng.org/) only works in Snow Leopard and hasn’t been updated in years.

**Comment by sg-s** [comment]
ok, thanks anyway!
