### ISSUE TITLE
Error message when attempting to crack

### ISSUE THREAD

**Issue by sg-s** [colemancda/Wi-Fi-Crack#7]
```
"/Applications/Wi-Fi Crack.app/Contents/Resources/aircrack-ng" -a 1 -b 00:23:97:20:19:65 /private/tmp/airportSniff*.cap
dyld: Library not loaded: /opt/local/lib/libssl.1.0.0.dylib
  Referenced from: /Applications/Wi-Fi Crack.app/Contents/Resources/aircrack-ng
  Reason: image not found
Trace/BPT trap: 5
```

running on 10.10.1

**Comment by ghost** [comment]
Hi I have the same issue. I am also interest in any answer to this.

**Comment by colemancda** [comment]
The embedded aircrack-ng binary shipped with this app can't find a dependent library. I would recommend installing aircrack-ng using Homebrew.

```
brew install aircrack-ng
```

Then modify the crack command from 

```
"/Applications/Wi-Fi Crack.app/Contents/Resources/aircrack-ng" -a 1 -b ...
```

to

```
aircrack-ng -a 1 -b ...
```

**Comment by ghost** [comment]
Hi thanks, how i do this ? I have to modify a text file like a .conf or something like that ?

**Comment by colemancda** [comment]
No just copy the command in terminal and modify it.

**Comment by ghost** [comment]
ok thanks it's works !

**Comment by sherifsaleh** [comment]
i got this error : 
/Applications/Wi-Fi Crack.app/Contents/Resources/aircrack-ng" aircrack-ng -a 1 -b ...
Invalid BSSID (not a MAC).
"/Applications/Wi-Fi Crack.app/Contents/Resources/aircrack-ng --help" for help.
